# Generated by Django 3.0.7 on 2020-07-22 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_created_by', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_removed_by', to=settings.AUTH_USER_MODEL)),
                ('user_related', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_owned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_agency',
            },
        ),
        migrations.CreateModel(
            name='AgreedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('bill_value', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_on', models.DateTimeField(blank=True, null=True)),
                ('planned_for_delivery', models.BooleanField(default=False)),
                ('expected_delivery_on', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Agency')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreedorder_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_agreed_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('image_url', models.CharField(blank=True, max_length=1024)),
                ('weight', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('origin', models.CharField(blank=True, max_length=256)),
                ('min_reserve_quantity', models.IntegerField(default=0)),
                ('removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_product',
            },
        ),
        migrations.CreateModel(
            name='RequestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('bill_value', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('approved', models.BooleanField(default=False)),
                ('apprived_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Agency')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestorder_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_request_order',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_storage',
            },
        ),
        migrations.CreateModel(
            name='StorageProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Product')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Storage')),
            ],
            options={
                'db_table': 'quickstart_storage_product_details',
            },
        ),
        migrations.CreateModel(
            name='RequestOrderProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Product')),
                ('request_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.RequestOrder')),
            ],
            options={
                'db_table': 'quickstart_request_order_product_details',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('gender', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_profile',
            },
        ),
        migrations.CreateModel(
            name='ProductUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('unit_type', models.CharField(blank=True, max_length=128, unique=True)),
                ('removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='productunittype_created_by', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productunittype_removed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_product_unit_type',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('product_type', models.CharField(blank=True, max_length=128, unique=True)),
                ('removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttype_created_by', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttype_removed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickstart_product_type',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.ProductType'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.ProductUnitType'),
        ),
        migrations.AddField(
            model_name='product',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_removed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MasterProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('from_date', models.DateField(blank=True)),
                ('to_date', models.DateField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterproductprice_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Product')),
            ],
            options={
                'db_table': 'quickstart_master_product_price',
            },
        ),
        migrations.CreateModel(
            name='AgreedOrderProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('agreed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.AgreedOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Product')),
            ],
            options={
                'db_table': 'quickstart_agreed_order_product_details',
            },
        ),
        migrations.AddField(
            model_name='agreedorder',
            name='request_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.RequestOrder'),
        ),
    ]
