# Generated by Django 3.0.7 on 2020-08-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
    ]
