# Generated by Django 3.0.7 on 2020-08-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200805_1811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
