# Generated by Django 3.0.7 on 2020-08-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyAreaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, unique=True)),
                ('longitude', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SalesmanAreaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
            ],
        ),
    ]
