# Generated by Django 3.0.7 on 2020-08-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
