# Generated by Django 3.0.7 on 2020-08-25 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0002_auto_20200824_1215'),
        ('areas', '0003_auto_20200825_1440'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areaagencydetails',
            unique_together={('area', 'agency')},
        ),
        migrations.AlterUniqueTogether(
            name='areasalesmandetails',
            unique_together={('area', 'salesman')},
        ),
    ]
