# Generated by Django 3.0.7 on 2020-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20200825_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name_latin',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
