# Generated by Django 3.0.7 on 2020-08-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'storages',
            },
        ),
        migrations.CreateModel(
            name='StorageProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.Storage')),
            ],
            options={
                'db_table': 'storage_product_details',
            },
        ),
    ]
