# Generated by Django 3.0.7 on 2020-08-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_storage_created_by'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storage',
            table='storages',
        ),
    ]
