# Generated by Django 3.0.7 on 2020-08-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('priority_level', models.CharField(choices=[('EM', 'Emergency'), ('UR', 'Urgent'), ('ST', 'Standard'), ('NO', 'Normal')], default='NO', max_length=2)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'agencies',
            },
        ),
    ]
