# Generated by Django 3.0.7 on 2020-08-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_auto_20200805_1122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agency',
            table='agencies',
        ),
    ]
