# Generated by Django 3.0.7 on 2020-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('bill_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('approved', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_on', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_on', models.DateTimeField(blank=True, null=True)),
                ('planned_for_delivery', models.BooleanField(default=False)),
                ('expected_delivery_on', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'agreed_orders',
            },
        ),
        migrations.CreateModel(
            name='AgreedOrderProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('request_amount', models.IntegerField(default=0)),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'agreed_order_product_details',
            },
        ),
        migrations.CreateModel(
            name='RequestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('bill_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'request_orders',
            },
        ),
        migrations.CreateModel(
            name='RequestOrderProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'request_order_product_details',
            },
        ),
    ]
