# Generated by Django 3.0.7 on 2020-08-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorderproductdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='requestorderproductdetails',
            name='request_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.RequestOrder'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='agency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
    ]
