# Generated by Django 3.0.7 on 2020-08-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_auto_20200807_1730'),
        ('products', '0001_initial'),
        ('orders', '0002_auto_20200807_1730'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorder',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestorder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreedorderproductdetails',
            name='agreed_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.AgreedOrder'),
        ),
        migrations.AddField(
            model_name='agreedorderproductdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='agreedorder',
            name='agency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
        migrations.AddField(
            model_name='agreedorder',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreedorder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreedorder',
            name='request_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.RequestOrder'),
        ),
    ]
