# Generated by Django 3.0.7 on 2020-08-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200823_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreedorder',
            name='request_order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.RequestOrder'),
        ),
    ]
