# Generated by Django 3.0.7 on 2020-08-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200805_1122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agreedorder',
            table='agreed_orders',
        ),
        migrations.AlterModelTable(
            name='requestorder',
            table='request_orders',
        ),
    ]
