# Generated by Django 3.0.7 on 2020-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200824_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreedorder',
            old_name='accepted',
            new_name='agency_accepted',
        ),
        migrations.RenameField(
            model_name='agreedorder',
            old_name='accepted_on',
            new_name='agency_accepted_on',
        ),
        migrations.AddField(
            model_name='agreedorder',
            name='agency_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreedorder',
            name='agency_rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreedorder',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'rejected'), (11, 'approved'), (20, 'agency_rejected'), (21, 'agency_approved'), (33, 'planned_for_delivery'), (44, 'delivered')], null=True),
        ),
    ]
