# Generated by Django 3.0.7 on 2020-08-26 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_agreedorder_confirm_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreedorder',
            name='confirm_paid_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreedorder_confirm_paid_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
