# Generated by Django 3.0.7 on 2020-08-07 17:30

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('from_date', models.DateField(blank=True)),
                ('to_date', models.DateField(blank=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master_product_price',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('name_latin', models.CharField(blank=True, max_length=256)),
                ('image', models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/')),
                ('weight', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('width', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('height', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('origin', models.CharField(blank=True, max_length=256)),
                ('min_reserve_quantity', models.IntegerField(default=0)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('product_type', models.CharField(blank=True, max_length=128, unique=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='ProductUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('unit_type', models.CharField(blank=True, max_length=128, unique=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_unit_type',
            },
        ),
    ]
