# Generated by Django 3.0.7 on 2020-08-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200805_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_latin',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
