# Generated by Django 3.0.7 on 2020-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200824_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunittype',
            name='code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
